# Site settings
title: Teamkita Media blogs
description: Fsteam cyber indonesia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Teamkita.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Firdaus siregar
user_description: hanya manusia yang ingin terus berkarya
user_title: abang daus
email: fsteamcyber@gmail.com
twitter_username: @anak_dayo
github_username:  mr614ck
gplus_username:  #
disqus_username: bgdaus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Beranda
    url: /
  - title: Seri
    url: /series
  - title: Tags
    url: /tags
  - title: Tentang aku
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
